sudo: required
dist: bionic

services:
  - elasticsearch
  - mysql

language: php

env:
  global:
    - CODE_COVERAGE=false
    - DI_COMPILE=false

matrix:
  include:
    - php: 7.3
      env: MAGENTO_VERSION=2.3.6-p1 # DI_COMPILE=true
    - php: 7.4
      env: MAGENTO_VERSION=2.4.2 CODE_COVERAGE=true

before_script:
  - export PATH=$PATH:$HOME/.composer/vendor/bin
  - composer config -a -g http-basic.repo.magento.com $MAGENTO_USERNAME $MAGENTO_PASSWORD
  - bash Test/Script/ManageDependencies.sh
  - bash Test/Script/Setup.sh

script:
  - if [ $CODE_COVERAGE == false ] && [ $DI_COMPILE == true ]; then php /tmp/magento2/bin/magento setup:di:compile; fi # Check for compilation errors
  - grunt phpcs
  - grunt exec:phraseTest
  - grunt exec:ciTests

after_success:
  - bash Test/Script/AfterSuccess.sh

cache:
  directories:
    - node_modules
    - $HOME/.download_cache
    - $HOME/.composer
    - $HOME/.cache/composer
